# MMC3 board with max. 8 FEI4s
ETH:
    ip : "192.168.10.16"
    udp_port : 4660
    tcp_port : 24
    tcp_connection : True

# Trigger
TRIGGER_CH0_TO_CH7:
    TRIGGER_MODE                         : 0  # Selecting trigger mode: Use trigger inputs/trigger select (0), TLU no handshake (1), TLU simple handshake (2), TLU data handshake (3)
    TRIGGER_SELECT                       : 31  # Selecting trigger input: RX2 (TDC loop-through) (8), RX1 (4), RX0 (2), MonHit/HitOR from chip 1/2/3/4/5 (1/2/4/8/16), disabled (0)
    TRIGGER_INVERT                       : 0  # Inverting trigger input: RX2 (TDC loop-through) (8), RX1 (4), RX0 (2), MonHit/HitOR from Adapter Card (1), disabled (0)
    TRIGGER_VETO_SELECT                  : 1  # Selecting trigger veto: RX1 (2), RX FIFO full (1), disabled (0)
    TRIGGER_HANDSHAKE_ACCEPT_WAIT_CYCLES : 3  # increase minimum trigger length
    TRIGGER_DATA_DELAY                   : 0  # Depends on the cable length and should be adjusted (run scan/tune_tlu.py)
    TRIGGER_THRESHOLD                    : 0  # Standard trigger minimum length

# TDC for high precision charge measurements
TDC0:
    EN_WRITE_TIMESTAMP   : 1  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

TDC1:
    EN_WRITE_TIMESTAMP   : 1  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

TDC2:
    EN_WRITE_TIMESTAMP   : 1  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

TDC3:
    EN_WRITE_TIMESTAMP   : 1  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

TDC4:
    EN_WRITE_TIMESTAMP   : 1  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

TDC5:
    EN_WRITE_TIMESTAMP   : 1  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

TDC6:
    EN_WRITE_TIMESTAMP   : 1  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

# FE-I4 command output
CMD_CH0_TO_CH7:
    OUTPUT_MODE : 3  # Selecting command output mode: positive edge (0), negative edge (1), Manchester Code according to IEEE 802.3 (2), Manchester Code according to G.E. Thomas (3)

# FE-I4 data receivers
CH0:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH1:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH2:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH3:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH4:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH5:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH6:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

CH7:
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)
