# MMC3 board with single FEI4 and max. 6 Mimosa26
ETH:
    ip : "192.168.10.16"
    udp_port : 4660
    tcp_port : 24
    tcp_connection : True

# Trigger
TRIGGER_FEI4:
    TRIGGER_MODE                         : 3  # Selecting trigger mode: Use trigger inputs/trigger select (0), TLU no handshake (1), TLU simple handshake (2), TLU data handshake (3)
    TRIGGER_SELECT                       : 0  # Selecting trigger input: MonHit/HitOR from module 0 (2), LEMO RX0 (1), disabled (0)
    TRIGGER_INVERT                       : 0  # Inverting trigger input: MonHit/HitOR from module 0 (2), LEMO RX0 (1), disabled (0)
    TRIGGER_VETO_SELECT                  : 1  # Selecting trigger veto: RX FIFO 0 full (2), FIFO full (1), disabled (0)
    TRIGGER_HANDSHAKE_ACCEPT_WAIT_CYCLES : 3  # Increasing minimum trigger length in TLU data handshale mode (preventing certain TLU flaws)
    TRIGGER_DATA_DELAY                   : 0  # TLU data handshake data delay depends on the cable length and should be adjusted with a delay scan (run scan/tune_tlu.py)
    TRIGGER_THRESHOLD                    : 0  # Standard trigger minimum length in clock cycles of the trigger/TLU FSM
    DATA_FORMAT                          : 0  # 31bit trigger number according to TRIGGER_MODE (0), 31bit time stamp (1), 15bit time stamp + 16bit trigger number (2)

# TDC for high precision charge measurements
TDC_FEI4:
    EN_WRITE_TIMESTAMP   : 0  # Writing trigger timestamp
    EN_TRIGGER_DIST      : 0  # Measuring trigger to TDC delay with 640MHz clock
    EN_NO_WRITE_TRIG_ERR : 0  # Writing TDC word only if valid trigger occurred
    EN_INVERT_TDC        : 0  # Inverting TDC input
    EN_INVERT_TRIGGER    : 0  # Inverting trigger input

# FE-I4 command output
CMD_FEI4:
    OUTPUT_MODE : 0  # Selecting command output mode: positive edge (0), negative edge (1), Manchester Code according to IEEE 802.3 (2), Manchester Code according to G.E. Thomas (3)

# FE-I4 data receiver
FEI4_RX:
    ENABLE_RX : 1  # Set to 0 if no FE is connected
    INVERT_RX : 0  # Inverting data input: disabled (0), enabled (e.g. for DBM modules) (1)

M26_RX1:
    EN : 1  # Set to 0 if no Mimosa26 is connected

M26_RX2:
    EN : 1  # Set to 0 if no Mimosa26 is connected

M26_RX3:
    EN : 1  # Set to 0 if no Mimosa26 is connected

M26_RX4:
    EN : 1  # Set to 0 if no Mimosa26 is connected

M26_RX5:
    EN : 1  # Set to 0 if no Mimosa26 is connected

M26_RX6:
    EN : 1  # Set to 0 if no Mimosa26 is connected
