
USB:
    bit_file       : "mio_gpac.bit"
    board_id       : 
    avoid_download : False

CMD:
    OUTPUT_MODE : 0  # 0: positive edge (default), 2: Manchester code

TLU:
    TRIGGER_MODE        : 0
    TRIGGER_SELECT      : 0 # CCPD_TDC_FROM_TDC, TDC_IN_FROM_TDC, LEMO_TRIGGER_FROM_TDC, MONHIT
    TRIGGER_INVERT      : 0
    TRIGGER_VETO_SELECT : 255 # VETO_IN, FIFO_FULL

TDC:
    ENABLE               : 0
    EN_WRITE_TIMESTAMP   : 0
    EN_TRIGGER_DIST      : 0
    EN_NO_WRITE_TRIG_ERR : 0
    EN_INVERT_TDC        : 0
    EN_INVERT_TRIGGER    : 0
